version: '3.7'

services:
  web:
    image: giant-isopod-vue:dev
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'

